### ISSUE TITLE
demande de fonctionnalité

### ISSUE THREAD

**Issue by duncan-valleix** [Domochip/WirelessTeleInfo#2]
je voulais savoir si il était possible de planifier un reboot sois sur l'interface sois via MQTT ?

**Comment by Davcail** [comment]
Ce n'est pas prévu mais tout à fait possible. Je vais ajouter une fonction de surveillance de la connexion Wifi pour la réinitialiser si besoin.

**Comment by Davcail** [comment]
Le reboot via l'interface Web est présent.

**Comment by duncan-valleix** [comment]
> Ce n'est pas prévu mais tout à fait possible. Je vais ajouter une fonction de surveillance de la connexion Wifi pour la réinitialiser si besoin.

se n'est pas pour sa que j'ai demandé si cela était possible, c'est juste que au bout d'une certaine durée de lecture des info des caractères se retrouve mise sur les ligne je joindrai des Screenshots, et la seul manière de résoudre sa a était pour moi de reboot le wemos

**Comment by duncan-valleix** [comment]
et je pensais faire une scénario, ou si il y a plus de caractère que prévu (ou même si c'est des lettre a la place des chiffre) sur tel ou tel ligne envoie une demande de reboot via mqtt

**Comment by Domochip** [comment]
Malhereusement, ce bug semble provenir de la librairie Teleinfo que j'utilise.
Je la met à jour et on verra si c'est corrigé.
