### ISSUE TITLE
PCB Wireless Teleinfo et mode standard linky

### ISSUE THREAD

**Issue by StephaneG38** [Domochip/WirelessTeleInfo#4]
Bonjour,
Bravo pour ce projet qui m'intéresse fortement car j'ai 3 compteurs à monitorer.
Pouvez vous m'indiquer ou trouver le PCB pour ce projet ?
Merci par avance
Stéphane

**Comment by Domochip** [comment]
Bonjour,
Désolé, je n'en ai pas en stock.
Si vous cherchez le PCB nu, je vous conseille de passer par OSHPark.
Bonne Journée

**Comment by StephaneG38** [comment]
Bonjour,
Merci pour le retour.
Stéphane

**Comment by StephaneG38** [comment]
Bonjour,
Je viens d'essayer avec mon linky en mode standard et rien ne remonte.
C'est normal ?
Merci par avance
Stéphane

**Comment by Domochip** [comment]
Dimanche, je regardais justement la librairie teleinfo que j'utilise et j'ai vu qu'elle semble gérer le linky en mode standard.
Je vais regarder rapidement si je peux ajouter cette option.

**Comment by StephaneG38** [comment]
Super merci beaucoup !!

**Comment by StephaneG38** [comment]
Pas de souci pour faire des tests !!

**Comment by Domochip** [comment]
Les premiers test ne sont pas concluant.
J'ai repassé un cable depuis mon compteur pour débugger.

**Comment by StephaneG38** [comment]
Merci pour ton travail !!

**Comment by Domochip** [comment]
C'est corrigé.
Mon linky est en mode historique.
Pourrais-tu essayer avec la pre-release que je viens de publier?
Il me faudrait ensuite le contenu de la page suivante : 
`http://{IP}/getAllLabel`

Il me semble que le numéro de série du compteur est ADSC. Je voudrais en être sûr.
N'oublie pas de modifier quelques caractères afin de ne pas publier ton numéro de série justement.
Merci

**Comment by StephaneG38** [comment]
OK je test

**Comment by StephaneG38** [comment]
J'ai ca avec des conexion et deconexion
![Capture d’écran 2022-01-26 191216](https://user-images.githubusercontent.com/38179281/151222122-899af122-5a53-4804-8dcc-ff6107fc060b.jpg)

**Comment by StephaneG38** [comment]
{"ADSC":"02q876531XXX"
,"NTARF":"ONJOURF"
,"SINSTS1":"CSINSTS2"
,"EASD04":"IIRMS1"
}

**Comment by StephaneG38** [comment]
En mettant historique il reste connecté
![image](https://user-images.githubusercontent.com/38179281/151222659-f42c1845-0595-4aa3-af81-95ddab667ac1.png)

**Comment by StephaneG38** [comment]
La valeur change :
021876531AAA
02q876531AAA
021x76531AAA

**Comment by StephaneG38** [comment]
Au fait je suis en tri

**Comment by Domochip** [comment]
Il faudrait connecter le D1Mini au PC par le micro USB est ouvrir le port série à 9600bps.
Au démarrage, il y a une sortie indiquant la connection au réseau Wifi, etc..
Ca m'interesse de savoir au bout de combien de temps ca explose.
Quelle est l'Upload Period (60secondes?)

**Comment by StephaneG38** [comment]
J'ai mis 5 s
![image](https://user-images.githubusercontent.com/38179281/151242587-f3f5c6d8-8c32-4311-92d9-b59bb3d25c39.png)

**Comment by StephaneG38** [comment]
Comment tu ouvre le port usb ?

**Comment by Domochip** [comment]
Avec putty par exemple.
5sec! ça me parait très court. Pourquoi pas 60sec?

**Comment by StephaneG38** [comment]
J'avais essayé avec putty mais la console reste noir 
![image](https://user-images.githubusercontent.com/38179281/151303552-bf8260c3-6ee7-437a-af03-13823271f87a.png)

J'ai essayé plusieurs câbles, prise USB pc et d'autre wemos mais c'est pareil
Avec mes 3 autres compteurs Sagem j'ai mis 5 secondes pour voir rapidement la mise en route des appareils branchés dessus.
Cela fonctionne très bien
je peux remettre à 60 s pour le linky s'il faut.

**Comment by StephaneG38** [comment]
Hello,
Tu as pu avancer ?

**Comment by Domochip** [comment]
Il faut que je scripte un faux compteur. Comme ca je pourrai débugger correctement.

**Comment by StephaneG38** [comment]
Ok
Merci pour ton aide 😉

**Comment by Domochip** [comment]
J'ai fait les tests.
J'observe un soucis avec la publication MQTT pour un Linky en mode Standard.
Mais si la partie Home Automation est désactivé : 
![image](https://user-images.githubusercontent.com/33293764/151668574-de35b6ca-1436-406e-8a7a-d9bae7fa6b45.png)

La page `http://{IP}/getAllLabel` me retourne bien les infos : 
![image](https://user-images.githubusercontent.com/33293764/151668598-3e196e96-c2b5-4a0b-926c-7b5f37ad59f2.png)

**Comment by StephaneG38** [comment]
Salut,
Du coup je ne peux pas passer par MQTT ?
Comment récupérer les infos alors ?

**Comment by Domochip** [comment]
Je regarde pour corriger le problème.
Mais ca m'interesserait de savoir si tu as la même chose?

**Comment by StephaneG38** [comment]
OK je test

**Comment by StephaneG38** [comment]
c'est un peu long car je dois remettre le programme dans l'ESP

**Comment by StephaneG38** [comment]
J'ai rien 
![image](https://user-images.githubusercontent.com/38179281/151670145-03bf0b95-eb7d-4a3c-911d-e177cd10cb30.png)

**Comment by Domochip** [comment]
Il faut vérifier le cablage avec le compteur

**Comment by StephaneG38** [comment]
ca marche avec mon rpi jeedom et le plugin teleinfo

**Comment by StephaneG38** [comment]
Oups j'ai pas mis l'ESP dans la boite

**Comment by StephaneG38** [comment]
J'ai ca 

{"ADSC":"02q876531XXX"
,"NTARF":"ONJOURF"
,"PRM":"%RGLAIS"
}

**Comment by StephaneG38** [comment]
On parle bien de ta dernière version Build version : 1.4.1/3.4.0 ?

**Comment by Domochip** [comment]
J'ai identifié le problème de publish MQTT.
Je viens de faire une nouvelle compil et je l'ai mise dans la pre-release : 
WirelessTeleInfo.v1.4.1-3.4.0**V2**.bin

**Comment by StephaneG38** [comment]
OK

**Comment by StephaneG38** [comment]
Du coup il faut tester avec MQTT ?

**Comment by Domochip** [comment]
oui

**Comment by StephaneG38** [comment]
OK je suis obligé de téléverser un firmware blank a chaque fois donc c'est un peu long

**Comment by Domochip** [comment]
ah bon?

**Comment by StephaneG38** [comment]
sinon j'ai du mal a me connecter en wifi en direct sur l'ESP

**Comment by StephaneG38** [comment]
J'ai pas essayer la mise à jour du firmware à partir de ta page web

**Comment by Domochip** [comment]
J'ai corrigé le défaut d'affichage sur la page Web => V3

**Comment by StephaneG38** [comment]
Toujours pas
![image](https://user-images.githubusercontent.com/38179281/151671608-b3b065c6-b9e5-48a0-918f-c1cf242ce875.png)

**Comment by StephaneG38** [comment]
J'ai fait avec
![image](https://user-images.githubusercontent.com/38179281/151671821-9239ebb5-f56f-4179-bf51-513f40812413.png)

**Comment by Domochip** [comment]
Le coup du '1' qui est remplacé par un 'q' est très étonnant.
surtout que le topic est construit à partir d'ADSC donc '02**q**876531' == '02187653**q**'

**Comment by StephaneG38** [comment]
Pareil

![image](https://user-images.githubusercontent.com/38179281/151671878-9a5fd3c4-29dd-46e8-bb93-b82fdfdd405c.png)

**Comment by Domochip** [comment]
les infos provenant du compteur sont vérifiés grâce au Checksum.
Donc si on les a, c'est qu'elles ont été validé par la librairie Teleinfo.
Si en utilisant le flash par la page Web ca ne fonctionne toujours pas, Il faut tester avec un autre module

**Comment by StephaneG38** [comment]
C'est pas tout le temps 
![image](https://user-images.githubusercontent.com/38179281/151671922-351ce003-0245-44b2-a485-2699ec639ce0.png)

**Comment by StephaneG38** [comment]
C'est pas tout le temps 
![image](https://user-images.githubusercontent.com/38179281/151671936-a1310d83-b79d-4d84-b2e2-1072dabb5d48.png)

**Comment by StephaneG38** [comment]
ca revient

![image](https://user-images.githubusercontent.com/38179281/151671963-b82a2504-359a-4591-8f93-9b897b1770d0.png)

**Comment by Domochip** [comment]
Faut voir avec un autre module d1 mini, ou vérifier que son alim est correcte aussi

**Comment by StephaneG38** [comment]
Je vais être obligé de te laisser
merci pour ton aide
A demain si tu es dispo
Bonne soirée
Stéphane

**Comment by StephaneG38** [comment]
Je vais essayer

**Comment by StephaneG38** [comment]
idem
![image](https://user-images.githubusercontent.com/38179281/151672109-0154743e-67aa-4eb2-82cf-ab94b3a70e33.png)

**Comment by StephaneG38** [comment]
Je te laisse 
Bonne soirée !

**Comment by StephaneG38** [comment]
Hello,
Le montage que j'utilise fonctionne bien avec mes 3 autres compteurs sagem.
![image](https://user-images.githubusercontent.com/38179281/151692995-36d6ad87-55f5-423c-b649-ee29bd68db8c.png)

**Comment by Domochip** [comment]
Quel en est le schéma?

**Comment by StephaneG38** [comment]
C'est un wifinfo réalisé par rolrider

https://forum.jeedom.com/viewtopic.php?t=21758

**Comment by StephaneG38** [comment]
Ci-dessous le schémas

![image](https://user-images.githubusercontent.com/38179281/151770569-eb5ca2bf-beb9-4afa-8505-8955cafb1573.png)

![image](https://user-images.githubusercontent.com/38179281/151770680-ca4db5fa-3fb8-4f8f-9294-1cee91f5bdc7.png)

**Comment by Domochip** [comment]
Coté schéma, tout à l'air bon.
Je viens de contacter Enedis, et en 2 minutes, ils ont passé mon compteur en mode Standard.

De mon coté, tout fonctionne bien : 
![image](https://user-images.githubusercontent.com/33293764/151785623-5af724c0-5d65-4a45-be82-812621e5e756.png)

Pas de lettre q (j'ai bien un 1 dans mon ADSC).
l'url getAllLabel fonctionne aussi correctement : 
![image](https://user-images.githubusercontent.com/33293764/151785996-088f9e1a-c3a8-4099-ab72-a072a0973c71.png)

**Comment by StephaneG38** [comment]
Réactif Enedis !!
De mon coté j'ai rebranché mon RPI avec Jeedom et téléinfo avec un modem USB carte electronique et tout fonctionne bien.
![image](https://user-images.githubusercontent.com/38179281/151786864-d9f96ec2-c219-48c6-90b2-a13c78c8d23f.png)

**Comment by Domochip** [comment]
un défaut d'affichage ? : 
![image](https://user-images.githubusercontent.com/33293764/151798393-716148e4-59d1-41af-a2ec-f29a0fc52a74.png)

**Comment by StephaneG38** [comment]
Je comprends pas !

**Comment by StephaneG38** [comment]
Par contre les valeurs des phases ne sont pas bonnes :

![image](https://user-images.githubusercontent.com/38179281/151802259-de97b181-6a67-443a-a3ee-5ca7367d232e.png)

**Comment by Domochip** [comment]
UMOY1 et URMS3 sont 2 étiquettes différentes.
et une puissance de 40000W sur la phase3 parait délirant oui

**Comment by StephaneG38** [comment]
Je vais refaire une config propre jeedom juste avec le teleinfo

**Comment by StephaneG38** [comment]
Sinon en mode historique cela fonctionne ?
Je peux voir avec enedis pour rebasculer. J'étais passé en standard pour avoir la production mais apparemment il faut faire encore une demande pour passer en producteur. Hors je suis en autoconso donc pas producteur et ils ne veulent pas faire la modif chez enedis. Donc EAIT est toujours à 0 en téléinfo alors que sur le compteur il indique 146 kwh

**Comment by Domochip** [comment]
Oui, En Historique, ça fonctionne aussi.

**Comment by StephaneG38** [comment]
Du coup je ne sais plus quoi faire !

**Comment by Domochip** [comment]
avec le RPi et Jeedom, en recréant l'équipement, y a-t-il toujours des étiquettes incorrectes?

**Comment by StephaneG38** [comment]
J'ai ca !
![image](https://user-images.githubusercontent.com/38179281/151864719-34805825-5a5e-4fca-bdfe-d0b84f5da6ea.png)

**Comment by StephaneG38** [comment]
Pour l'intensité instantanée je pense qu'il faut prendre :
![image](https://user-images.githubusercontent.com/38179281/151864948-cf21ac59-084b-4659-b18d-4114db89d6b4.png)

Ce qui me semble correspondre au compteur

**Comment by Domochip** [comment]
J'utilise le dernier doc d'Enedis : Enedis-NOI-CPT_54E.pdf
As-tu un besoin particulier d'avoir l'intensité?

En passant le plugin en débug, ca sort du log interessant je pense

**Comment by StepG38** [comment]
[log teleinfo.zip](https://github.com/Domochip/WirelessTeleInfo/files/7974439/log.teleinfo.zip)

**Comment by Domochip** [comment]
tout à l'air OK
Attention, il te faut supprimer ce log car il contient des infos sensibles!

**Comment by Domochip** [comment]
Je te conseille de faire un test avec tasmota : 
https://tasmota.github.io/docs/Teleinfo/

**Comment by StepG38** [comment]
Bonjour à tous,
Petit retour sur mon problème de swap qui n'est plus.
Je suis simplement passé sur un RPI 4 2Go (et oui impossible de trouver des 4Go) et le swap est à 0

![image](https://user-images.githubusercontent.com/38179281/151976760-582cd494-6417-4b8d-8a0d-1eea756d9ea7.png)

Stéphane

**Comment by Domochip** [comment]
?

**Comment by StephaneG38** [comment]
Je vais tester avec Tasmota dans l'après midi

**Comment by StephaneG38** [comment]
Hello,
Test avec Tasmota 

![image](https://user-images.githubusercontent.com/38179281/151996426-9ebcfed3-a216-4d7d-a0f6-c68f7da6f011.png)


![image](https://user-images.githubusercontent.com/38179281/151996336-c37b29df-10db-4b89-8fd6-c17cf0b31204.png)

Aprés j'ai fait dans les commandes : EnergyConfig standard

`00:00:00.001 HDW: ESP8266EX
00:00:00.050 CFG: Loaded from flash at F5, Count 31
00:00:00.055 QPC: Count 1
00:00:00.064 Project tasmota - Tasmota Version 2022.01.3(teleinfo)-2_7_4_9(2022-02-01T14:35:17)
00:00:00.064 TIC: RX on GPIO13, baudrate 9600
00:00:00.106 SNS: Hardware Serial
00:00:00.106 TIC: using hardware serial
00:00:00.521 WIF: Connecting to AP1 SG Channel 6 BSSId 60:35:C0:C4:2A:96 in mode 11n as tasmota-9F52DB-4827...
00:00:03.501 WIF: Connected
00:00:03.752 HTP: Web server active on tasmota-9F52DB-4827 with IP address 192.168.1.16
16:40:19.298 MQT: Attempting connection...
16:40:19.317 MQT: Connected
16:40:19.319 MQT: tele/tasmota_9F52DB/LWT = Online (retained)
16:40:19.321 MQT: cmnd/tasmota_9F52DB/POWER = 
16:40:19.331 MQT: tele/tasmota_9F52DB/INFO1 = {"Info1":{"Module":"Generic","Version":"2022.01.3(teleinfo)","FallbackTopic":"cmnd/DVES_9F52DB_fb/","GroupTopic":"cmnd/tasmotas/"}}
16:40:19.335 MQT: tele/tasmota_9F52DB/INFO2 = {"Info2":{"WebServerMode":"Admin","Hostname":"tasmota-9F52DB-4827","IPAddress":"192.168.1.16"}}
16:40:19.338 MQT: tele/tasmota_9F52DB/INFO3 = {"Info3":{"RestartReason":"Software/System restart"}}
16:40:21.455 QPC: Reset
16:40:24.417 MQT: tele/tasmota_9F52DB/STATE = {"Time":"2022-02-01T16:40:24","Uptime":"0T00:00:11","UptimeSec":11,"Vcc":2.832,"Heap":26,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"MqttCount":1,"Wifi":{"AP":1,"SSId":"SG","BSSId":"60:35:C0:C4:2A:96","Channel":6,"Mode":"11n","RSSI":100,"Signal":-27,"LinkCount":1,"Downtime":"0T00:00:05"}}
16:40:24.427 MQT: tele/tasmota_9F52DB/SENSOR = {"Time":"2022-02-01T16:40:24","ENERGY":{"TotalStartTime":"2022-02-01T16:07:50","Total":0.000,"Yesterday":0.000,"Today":0.000,"Period": 0,"Power": 0,"Current":0.000},"TIC":{}}
16:41:48.269 CMD: EnergyConfig
16:41:48.273 TIC: Settings Mode:standard, RX:GPIO13, EN:None, Raw:noraw, Skip:0, Limit:0
16:41:48.277 MQT: stat/tasmota_9F52DB/RESULT = {"EnergyConfig":"Done"}
`

Mais toujours rien !!

![image](https://user-images.githubusercontent.com/38179281/152002642-22417d17-01c8-4d32-bbf5-e6680251aeed.png)

Dans MQTT 

![image](https://user-images.githubusercontent.com/38179281/152000898-f17e756c-6c85-486d-a3d8-7717ff59f894.png)

**Comment by StephaneG38** [comment]
Je viens de tester avec le firmware de Teleinfo 9.1.1 by Nicolas Bernaerts
[https://github.com/NicolasBernaerts/tasmota/tree/master/teleinfo](url)


![image](https://user-images.githubusercontent.com/38179281/152009695-630dd3c0-ca71-4c7b-a16c-059b8d4331de.png)

J'ai 230 v !! Super !!

Et des messages de partout dans MQTT

![image](https://user-images.githubusercontent.com/38179281/152010081-7f443e79-0a56-4e0e-a74c-7eacc2e50530.png)


Je dois vraiment être nul !!!!

**Comment by StephaneG38** [comment]
EUREKA !!!!
J'ai fait un proto suivant le schéma V2.2 et utilisé la dernière release WirelessTeleInfo.v1.4.1-3.4.1 et tout semble fonctionner !!

![image](https://user-images.githubusercontent.com/38179281/152133116-2346228b-6fc3-45ad-b34c-e7914798eaaf.png)


![image](https://user-images.githubusercontent.com/38179281/152132422-72fbafb3-78ea-4542-b294-f2173c7418d5.png)


![image](https://user-images.githubusercontent.com/38179281/152132634-d3f72bda-f4fd-4acd-8523-30f56761e1c7.png)


GRAND MERCI pour ta patience et ton aide.
Stéphane

**Comment by Domochip** [comment]
cool!!!!
ça, c'est la persévérence. :-D

**Comment by StephaneG38** [comment]
Effectivement j'ai pas lâché sur ce coup la mais beaucoup de temps passé !
Encore merci pour ton aide et bravo pour le travail que tu as fait sur ce projet.
A bientôt
Stéphane
