### ISSUE TITLE
Home Assistant auto discovery

### ISSUE THREAD

**Issue by azrod** [Domochip/WirelessTeleInfo#5]
Bonjour,

Pourriez-vous ajouter une option pour publier dans MQTT l'auto configuration des entités HomeAssistant ? 

En effet en publiant dans le topic de home assistant par exemple : **homeassistant/sensor/teleinfo/hchc/config** il est possible de configurer une entités de type sensor de façon automatique. 

Voici le configuration JSON "Type" pour un sensor a publier 
```
{
    "availability": [
        {
            "topic": "teleinfo/connected",
            "payload_available": "1",
            "payload_not_available": "0"
        }
    ],
    "device": {
        "identifiers": [
            "<SerialNumber>"
        ],
        "manufacturer": "DOMOCHIP",
        "model": "WTELEINFO",
        "name": "WTELEINFO",
        "sw_version": "<WTELEINFO_VERSION>"
    },
    "enabled_by_default": true,
    "json_attributes_topic": "teleinfo/HCHC",
    "name": "Heures Creuses",
    "device_class": "energy",
    "state_class": "total_increasing",
    "state_topic": "teleinfo/HCHC",
    "unique_id": "wteleinfo_<SerialNumber>_hchc",
    "unit_of_measurement": "Wh",
    "force_update": true
}
```

L'avantage de cette déclaration c'est qu'on déclare un "appareil" dans home assistant dans lequel on retrouvera tous les sensors associés. 
<img width="1642" alt="image" src="https://user-images.githubusercontent.com/13660462/191113042-11c87918-1c7f-4ea3-b151-3945819dec71.png">

Voici le JSON que j'ai utilisé pour l'exemple 
```
{
    "availability": [
        {
            "topic": "teleinfo/connected",
            "payload_available": "1",
            "payload_not_available": "0"
        }
    ],
    "device": {
        "identifiers": [
            "00e609eb"
        ],
        "manufacturer": "DOMOCHIP",
        "model": "WTELEINFO",
        "name": "WTELEINFO",
        "sw_version": "1.4.1/3.4.1"
    },
    "enabled_by_default": true,
    "json_attributes_topic": "teleinfo/HCHC",
    "name": "Heures Creuses",
    "device_class": "energy",
    "state_class": "total_increasing",
    "state_topic": "teleinfo/HCHC",
    "unique_id": "wteleinfo_00e609eb_hchc",
    "unit_of_measurement": "Wh",
    "force_update": true
}

```

Si nécessaire voici la documentation pour l'auto configuration d'une entités de type sensor dans HomeAssistant : [https://www.home-assistant.io/integrations/sensor.mqtt/](https://www.home-assistant.io/integrations/sensor.mqtt/) et la documentation plus générale sur le Discovery MQTT [https://www.home-assistant.io/docs/mqtt/discovery/](https://www.home-assistant.io/docs/mqtt/discovery/)

Merci

**Comment by Domochip** [comment]
Bonjour,

Ce projet viens de passer à Tasmota. l'intégration home assistant est disponible sur tasmota
